In [4]:
# Problem with ddcdd contents where d=digit c=char
import os
import json
from collections import namedtuple


subjectData = []
subject = []
# whole subject set
wholeSubject =set()
# cleaned subject set 
cleanedWholeSubject = set()

for i in os.listdir("./2017"):
    if i.endswith('.json'):
        with open("./2017/" + i,encoding="utf8") as f:
            lines = f.readlines()
            if(len(lines) == 0): continue
            for line in lines:
                x = json.loads(line, object_hook=lambda d: namedtuple('X', d.keys())(*d.values()))
                #print(x[1]) 
                temp = x[1].subject
                wholeSubject.update(temp)
                # remove numbers and chars not subject names
                cleanedTemp = [x for x in temp if not any(c.isdigit() for c in x)]
                cleanedWholeSubject.update(cleanedTemp)
                subjectData.append(cleanedTemp) 
                
                
                #for line in lines[1:2]:
                 #   print(line)

In [18]:
import numpy as np
ListCleanedWholeSubject= list(cleanedWholeSubject)
onHotSubjectList = []
# Iterate each doc 
for i in range(len(subjectData)):
    # itearte over the list of subjects in each doc 
    docSubjectList = [0] *  len(ListCleanedWholeSubject)
    for j in range(len(subjectData[i])):
        for k in range(len(ListCleanedWholeSubject)):
            if (subjectData[i][j]==ListCleanedWholeSubject[k]):
                docSubjectList[k]=1
                    
    onHotSubjectList.append(docSubjectList)


In [19]:
# Onehot subject list nparray  
#type(onHotSubjectList[0])
onHotArray = np.array(onHotSubjectList)
print(onHotArray)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [26]:
# Check if correct
for i in range(len(onHotArray)):
    if len(onHotArray[i])!=161:
        print("row",i," hsa problem with length")
    if sum(onHotArray[i])!=len(subjectData[i]):
        print("row",i," hsa problem with matching")


In [30]:
subjectData[3]

['Mathematics - Quantum Algebra', 'Mathematics - Combinatorics']

In [25]:
print(sum(onHotArray[3]))

2


In [36]:
target = "Mathematics"
for s in subjectData[3]: 
    if target in s:
        print(1)

1
1


In [38]:
target in subjectData[3][1]

True

In [39]:
subjectData

[['Nuclear Theory', 'Nuclear Experiment'],
 ['Mathematics - Statistics Theory'],
 ['Condensed Matter - Strongly Correlated Electrons'],
 ['Mathematics - Quantum Algebra', 'Mathematics - Combinatorics'],
 ['Mathematics - General Mathematics'],
 ['Mathematics - Algebraic Geometry'],
 ['Computer Science - Databases'],
 ['Computer Science - Databases'],
 ['Physics - Instrumentation and Detectors',
  'High Energy Physics - Experiment'],
 ['Physics - Instrumentation and Detectors',
  'High Energy Physics - Experiment'],
 ['Condensed Matter - Soft Condensed Matter', 'Physics - Geophysics'],
 ['Physics - Atomic Physics'],
 ['Mathematics - Functional Analysis'],
 ['Mathematics - Group Theory'],
 ['Condensed Matter - Mesoscale and Nanoscale Physics'],
 ['Condensed Matter - Soft Condensed Matter', 'Physics - Chemical Physics'],
 ['Quantum Physics', 'Mathematical Physics'],
 ['Physics - Data Analysis, Statistics and Probability',
  'Physics - Biological Physics',
  'Physics - Chemical Physics'],
 

In [40]:
# Total number of subjects
NUM_OF_SUBJECTS = 8
SUBJECT_LIST = ['Physics', 'Mathematics', 'Computer Science', 'Quantitative Biology', 'Quantitative Finance', 'Statistics', 'Electrical Engineering and Systems Science', 'Economics']
for i in range(len(subjectData)):
    docSubjectList = [0] *  NUM_OF_SUBJECTS
    # iterate subjects 
    for j in range(len(subjectData[i])):
        if()
        
        

SyntaxError: unexpected EOF while parsing (<ipython-input-40-4bed26205ac4>, line 1)

In [47]:
SUBJECT_LIST = ['Physics', 'Mathematics', 'Computer Science', 'Quantitative Biology', 'Quantitative Finance', 'Statistics', 'Electrical Engineering and Systems Science', 'Economics']
onHotReducedSubjectList = []
# Iterate each doc 
for i in range(len(subjectData)):
    # itearte over the list of subjects in each doc 
    docSubjectList = [0] *  len(SUBJECT_LIST)
    for j in range(len(subjectData[i])):
        for k in range(len(SUBJECT_LIST)):
            if (SUBJECT_LIST[k] in subjectData[i][j]):
                docSubjectList[k]=1
                    
    onHotReducedSubjectList.append(docSubjectList)

In [49]:
onHotReducedSubjectList

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 1, 0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 1, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 1, 0, 0],
 

In [51]:
subjectData[0]

['Nuclear Theory', 'Nuclear Experiment']